### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by babakfp** [morethanwords/tweb#101]
What is the difference between this version (K version) and the Z version?

**Comment by chimo666** [comment]
Por favor tengo problemas para configurar mi telegram.Las letras estan muy chicas y cuando le doy para ampliarlas se juntan todas y no puedo distinguir nada,Agradeceria enormemente que alguna persona me pueda ayudar a ver que estoy haciendo mal. muchas gracias.Bendiciones

**Comment by babakfp** [comment]
> Por favor tengo problemas para configurar mi telegram.Las letras estan muy chicas y cuando le doy para ampliarlas se juntan todas y no puedo distinguir nada,Agradeceria enormemente que alguna persona me pueda ayudar a ver que estoy haciendo mal. muchas gracias.Bendiciones

Are you using the web version?
¿Estás usando la versión web?
