### ISSUE TITLE
[BUG] `npm start` not compiling

### ISSUE THREAD

**Issue by matthiasaechtner** [morethanwords/tweb#107]
Error message:
"Module not found: Error: Can't resolve '../fileManager'"

Fix:
Please rename
`git mv tweb/src/lib/filemanager.ts tweb/src/lib/fileManager.ts`
(capitalization)
so it `npm` runs again on all systems.

cheers,
Matthias

**Comment by morethanwords** [comment]
Fixed, thank you!
