### ISSUE TITLE
[Feature Request] Support web bots

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#117]
**Is your feature request related to a problem? Please describe.**
Web bots are now supported in the native Telegram clients, but not in Telegram Web K.

**Describe the solution you'd like**
Telegram Web K should add support for web bots.

**Comment by amhoba** [comment]
We need this please guys.

Please add bot token login support. I use telegram bots as a support mechanism for my channel and I need an interface for them. to being able to see users, interact with them etc.

If you could and see this as a simple feature (and not time consuming) please add it. thank you.
