### ISSUE TITLE
[BUG] ReplyKeyboardMarkup without scroll container

### ISSUE THREAD

**Issue by vireks** [morethanwords/tweb#123]
**Describe the bug**
ReplyKeyboardMarkup (https://core.telegram.org/bots/api#replykeyboardmarkup) without scroll container. There are 130 buttons on my screenshot, but we can see only 9.

**To Reproduce**
1. Go to example bot (https://t.me/my_ext_bot?start=30)
2. Click on 'Open in Web' => 'Start' => 'Show chat keyboard'

**Screenshots**
![image](https://user-images.githubusercontent.com/17138087/165756238-c4f8309a-08c4-4888-848c-cd4a1f1368e6.png)
![image](https://user-images.githubusercontent.com/17138087/165767265-163f1f54-a713-4720-a9ee-54bcc4a1bff8.png)

**Desktop (please complete the following information):**
 - Windows 10
 - chrome
 - 100.0.4896.127

**Comment by morethanwords** [comment]
Fixed.
