### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maiahmedd** [morethanwords/tweb#125]
**Describe the bug**
The call feature isn't working 

**To Reproduce**
1. Go to 'any profile to make a call'
2. Click on 'the call symbol"
3. It will give you "connecting" when the other person answers the call
5. See error

**Expected behavior**
to connect and start the calling 
**Screenshots**

**Desktop (please complete the following information):**
 - Version [1.4.3] (175)

**Additional context**
the version is needed to update

**Comment by valerio-bozzolan** [comment]
Please try a different connection method (e.g. Wi-Fi, or another mobile phone. What is your geographical area?

Also please improve the title to give more sense to your bug request.
