### ISSUE TITLE
[BUG] Some notifications from muted chats are displayed

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#127]
**Describe the bug**
If a chat is muted, I don't want to see any notifications from it. In fact, I see a notification when a message is pinned.

**To Reproduce**
1. Mute a chat (e.g. a group).
2. Have someone pin a message in it.

**Expected behavior**
The chat is muted, so there should be no notification.

**Version**
Telegram WebK 1.4.3 (175)

**Comment by morethanwords** [comment]
It is intended behavior, you also get notifications on any other client.
