### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Rehan989** [morethanwords/tweb#130]
**Is your feature request related to a problem? Please describe.**
The Logout Button is not present in the telegram web, i have to open telegram app on mobile phone again and again to logout on devices. It may have been convenient if there is a logout button on telegram web

**Comment by NastyaGrifon** [comment]
You can actually log out without using Devices section. You can find it in the Settings => Three button sandwitch in the top right corner => Logout. It would be helpful if Logout button was easier and more intuitive to find.

![Screenshot_20220614_123622](https://user-images.githubusercontent.com/14854919/173533111-bf54bc7e-3a4c-45fc-9563-1f25fdb9ecfb.jpg)
