### ISSUE TITLE
[BUG] Links in spoilers should not be clickable until the spoiler is uncovered

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#133]
**Describe the bug**
Suppose that there is some text that is hidden using spoiler formatting, and this text includes a link. The link is not visible because of the spoiler. When clicking on this (hidden) link, the user expect it to be revealed. Instead, the click is handled by the link itself, so the user navigates to the link's destination.

**To Reproduce**
1. View a message with a link within a spoiler.
2. Click on that link.
3. The link is activated while still hidden.

**Expected behavior**
The link should become visible. The second click (while the link is visible) should activate it.

**Desktop (please complete the following information):**
 - Telegram WebK 1.4.3 (177)

**Comment by morethanwords** [comment]
Thank you for the report! Has been fixed in latest update.
