### ISSUE TITLE
[BUG] Sometimes not all chats appear in the chat list

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#134]
**Describe the bug**
When loading Telegram Web K, sometimes only a small number of chats appears in the chat list. Refreshing the page fixes the problem.

**To Reproduce**
I found no way to reliably reproduce this issue. It seems to appear randomly when loading Telegram Web K.

**Desktop (please complete the following information):**
 - Browser: Firefox 91.10.0
 - Version: Telegram Web K 1.4.3 (177)

**Additional context**
This looks like a state synchronization issue. After reloading the page, it displays an old state briefly, but then updates to the current state.

**Comment by morethanwords** [comment]
Fixed.
