### ISSUE TITLE
[Feature Request] Show media in bot descriptions

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#136]
**Is your feature request related to a problem? Please describe.**
Now, it is possible to add an image of a GIF to a bot description. Unfortunately, Telegram Web K doesn't show it.

**Describe the solution you'd like**
Telegram Web K should support displaying media in bot descriptions.

**Comment by fromaline** [comment]
May you provide a bot with an image or a GIF in its description? I haven't been able to find any.

**Comment by abacabadabacaba** [comment]
For example, [@Video_Saver_robot](https://t.me/Video_Saver_robot), and it seems to work in Telegram Web K right now (the GIF in the description is visible).
