### ISSUE TITLE
[Feature Request] Can't see quotes once viewed

### ISSUE THREAD

**Issue by Porkechebure** [morethanwords/tweb#137]
Easy as:
You get quoted, you click the quote (@) icon and for any reason you miss it (scrolling page, changing group, browser unexpectedly closes, whatever).

You are not able to see the quote anymore and maybe a hundred or more message have passed by if the group is big.

Would be nice to be able to return to your previous quotes.
Not necessarily every quote, but at least last X quotes?

**Comment by morethanwords** [comment]
You're welcome to create a card for it on [Suggestions Platform](https://suggestions.telegram.org/). Currently Telegram doesn't have such functionality.
