### ISSUE TITLE
Folders context menu is missing

### ISSUE THREAD

**Issue by vitaly-zdanevich** [morethanwords/tweb#14]
On Android I can `Edit folder`, but not on this web client.

**Comment by morethanwords** [comment]
What do you mean by "not on this web client"? You can find this in **Settings** > **Chat Folders** > **Folder**
![image](https://user-images.githubusercontent.com/25210241/116817588-c7fe8d80-ab6f-11eb-8424-655488706a7f.png)

**Comment by vitaly-zdanevich** [comment]
Wow, ok, sorry. Like on Android I just tried to click on the tab.
