### ISSUE TITLE
[BUG] unable to go to message after doing a search from inside "Saved Messages"

### ISSUE THREAD

**Issue by ffigari** [morethanwords/tweb#140]
After doing a search from inside "Saved Messages" (not from the general search input) a match is found and shown but I can't go to the message. It says _N messages found_ and then for each match it shows an entry with just my name (but no content). On click nothing happens. On right click the default browser's menu opens.

To reproduce:
1. go to "Saved Messages"
2. make a search for which you know you will have a match
3. see empty non-clickable box for each match

I would expect to at least be able to go to the matched message when clicking it. It would also make sense for a preview of the message to be shown.

![image](https://user-images.githubusercontent.com/14151594/175752668-ffd879d0-0071-4042-84ff-6d8174fbc095.png)

 - OS: Manjaro
 - Browser: Firefox
 - Version: 101

**Comment by morethanwords** [comment]
Fixed in 1.5.0 (180), thank you.
