### ISSUE TITLE
[BUG] Telegram Web K doesn't work

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#141]
**Describe the bug**
After the latest update, Telegram Web K stopped working completely. Here is what I see:

![image](https://user-images.githubusercontent.com/8302078/175790041-7101c09b-266f-4db9-b991-309d042b627f.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Firefox 91.10.0esr

**Comment by morethanwords** [comment]
Hi! Is it still not working? I'm testing Firefox 90 on Ubuntu, everything is fine.

**Comment by abacabadabacaba** [comment]
Works now, thanks.
