### ISSUE TITLE
[BUG] scheduled massage read Error

### ISSUE THREAD

**Issue by gbV47x** [morethanwords/tweb#143]
**Describe the bug**

after recently updates--about 1.5.0(180) , webk could not read all scheduled messages

**To Reproduce**
1. open a chat
2. Click on 'scheduled message'
3. you would find that only part of all mssages displayed on your browser(all messages would be here before recently updates) 
4. See error.. 

**Expected behavior**
All messages would be read and displayed in 'scheduled msgs' window, isn't it? 

**Screenshots**
❌

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Firefox/chrome
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android
 - Browser: Firefox/chrome
 - Version: Latest

**Additional context**
❌

**Comment by morethanwords** [comment]
Thank you for the report! Fixed in 1.5.0 (183).
