### ISSUE TITLE
[Feature Request]增加中文add Chinese

### ISSUE THREAD

**Issue by yes567** [morethanwords/tweb#149]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NB112211** [comment]
Please add the Chinese language, or you can support the voice pack to support him
求加加入中文语言，或者您可以支持语音包来支持他

**Comment by qiangweihewu** [comment]
Is it possible to add it? There is already a beta Simple Chinese version on telegram official translation platform.

**Comment by yes567** [comment]
> 请加中文，或者支持语音包支持他 求加入中文语言，或者您可以支持语音包来支持他

Where?

**Comment by qiangweihewu** [comment]
https://translations.telegram.org/zh-hans
