### ISSUE TITLE
[BUG] Cannot permanently mute notifications in a group

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#162]
**Describe the bug**

When using the "Mute" button, it only works when selecting a limited duration (e.g. "For 1 Day"). When selecting "Forever", it doesn't work (notifications are not muted at all).

**To Reproduce**
1. Open a chat,
2. Click the "Mute" button,
3. Select "Forever", click "Mute".
4. Notifications are not muted.

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Firefox 102.3.0esr
 - Version: Telegram Web K 1.5.0 (241)

**Comment by morethanwords** [comment]
Thank you for the report! Has been fixed in build 243.
