### ISSUE TITLE
[BUG] Music files cannot be downloaded

### ISSUE THREAD

**Issue by Vozf** [morethanwords/tweb#163]
**Describe the bug**
I can't download music files. there is no "Download" after right click. https://webk.telegram.org/
Possibly related to https://github.com/morethanwords/tweb/pull/161

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fromaline** [comment]
It seems like an easy fix to me, I'll take it.
