### ISSUE TITLE
I want to know how to use appDownloadManager DownloadMedia to get a complete file blob

### ISSUE THREAD

**Issue by po-lan** [morethanwords/tweb#168]
I want to know how to use "appDownloadManager.DownloadMedia" to get a complete file blob
When I use this function to obtain the blob, there is no problem in the small file,
     but if the file is a little larger, there is only the first blob

this is my code 
![image](https://user-images.githubusercontent.com/42771836/197377771-041a245a-7c06-4c9f-9518-dae605165380.png)

I can use this code to get a complete picture, but when I use this code to try to get a video, I can never get all of it
I have tried many times, but I can't help it, so I come here for help

**Comment by morethanwords** [comment]
You should use `appDownloadManager.downloadToDisc` without thumb in options to download the original file.
