### ISSUE TITLE
Important groups are removed randomly in by the server

### ISSUE THREAD

**Issue by ILG2021** [morethanwords/tweb#179]
Recently, some very important groups of mine were disappear when I was in a group call or just send some texts. It caused me a great loss, I don't think I violated any of the terms of service. It just happened recently. Other messenger platform will never dismiss groups even the owner is blocked. Even worse, Telegram give nothing about the removing and it happened randomly, it scared me. Telegram don't have customer service, so I tried to send emails to the support email, no response. I don't know how to deal with the problem. I think it is may be caused by a bug of the server. 
And when I use telegram k to make group calls, I set stereo of the browser and share the system sound on my pc, like playing a music, sometimes the system sound will disappear. Then other participant open and close the microphone will hear the sound again. It is a another big potential bug of telegram K.

**Comment by morethanwords** [comment]
You should reach Telegram Support regarding this if it's still actual for you.
