### ISSUE TITLE
[BUG] stuck when upload big size pictures

### ISSUE THREAD

**Issue by gbV47x** [morethanwords/tweb#186]
**Describe the bug**

when upload big pictures, say, 20MB/pic*30pics, UI would get into stuck

**To Reproduce**
1. Go to some chat
2. Click on "upload file"
3. Select 30 or more pictures (every picture more than 15 MB), and confirm

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by morethanwords** [comment]
Thank you for the report! Fixed in 1.7.0 (280).
