### ISSUE TITLE
[BUG] Some videos won't play

### ISSUE THREAD

**Issue by erayrafet** [morethanwords/tweb#190]
**Describe the bug**
Many videos don't start.

**To Reproduce**
1. Go to [this video example](https://t.me/techleakszone/1702)
2. Click on the play button.

**Screenshots**
There are errors in the DevTools.
![image](https://user-images.githubusercontent.com/34194191/212458702-fadcc3c3-b9cc-4174-8042-289657d048d0.png)

**Desktop (please complete the following information):**
 - OS/Browser: ChromeOS Flex
 - Version 110 Beta

**Additional context**
The same issue has existed for a few months and could be observed in Chrome 109. No such problem in Telegram Web Z.

**Comment by morethanwords** [comment]
Thank you for the report. This concrete issue has been fixed week ago, however, there are still some videos that can't be played in some browsers, unless developers will fix the ffmpeg.

**Comment by erayrafet** [comment]
> Thank you for the report. This concrete issue has been fixed week ago, however, there are still some videos that can't be played in some browsers, unless developers will fix the ffmpeg.

Thanks!
What's the ffmpeg issue in question?

**Comment by morethanwords** [comment]
> Thanks! What's the ffmpeg issue in question?

That's what I'm getting in `error` property of `HTMLVideoElement`:
`DECODER_ERROR_NOT_SUPPORTED: Audio configuration specified 2 channels, but FFmpeg thinks the file contains 1 channels`

Chrome 109, Windows 11.
