### ISSUE TITLE
[BUG] login session is not saved after browser is closed

### ISSUE THREAD

**Issue by ilyapashuk** [morethanwords/tweb#192]
**Describe the bug**

when browser is closed, login session gets forgotten and at the next time I need to login again

**To Reproduce**
1. go to web.telegram.org
2. login by the phone number
3. when push notification request pops up, simply close it without answering anything, or press deny.
4. close the web browser
5. wait few minutes, start the browser and open the teleggram web again

**Expected behavior**
session should be resumed automaticly

**Desktop (please complete the following information):**
 - OS: [e.g. MS Windows]
Windows 10 ltsc 1809, firefox 108.
**Smartphone (please complete the following information):**

**Additional context**

**Comment by ilyapashuk** [comment]
there is the following after log after login in:

[236.385] [API] Error 401 AUTH_KEY_UNREGISTERED 2 4 upload.getFile 
Object { location: {…}, offset: 0, limit: 131072, flags: 0 }
946.d26679f97a8960b11df8.bundle.js:1:9517
    u https://web.telegram.org/k/946.d26679f97a8960b11df8.bundle.js:1
    f https://web.telegram.org/k/mtproto.worker.a47a496f3c7a877087bb.chunk.js:1

<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions. react-redux.js:881:13
    Redux 3
    React 13

**Comment by ti1em** [comment]
مرحبا لدي مشكله واتمنى منكم الرد السريع والمساعده  لقد سجلت خروج من تليغرام  ولا استطيع الدخول اعتقد ان احدهم اضاف كلمه مرور تحقق بخطوتين  الى حسابي  والان لا يمكنني الدخول
@ruslan-gennadievich 
@ilyapashuk

**Comment by morethanwords** [comment]
I don't have React, neither Redux. The problem you are facing is mostly about caching settings of your browser.
