### ISSUE TITLE
TIYm

### ISSUE THREAD

**Issue by ti1em** [morethanwords/tweb#195]
![Screenshot_٢٠٢٣٠١٢١-٢٣٣٣٤١_Telegram](https://user-images.githubusercontent.com/123328413/213941620-9071ccf2-5b98-44bc-9373-521f102a8314.jpg)
مرحبا لدي مشكله هل بأمكانكم المساعده اعتقد ان احهم قد  اضاف كلمه مرور الى حساب التلكرام الخاص بي  وانا الان لا استطيع فتحه  ولا اريد ان احذف الحساب انا احتاجه

**Comment by morethanwords** [comment]
I'm sorry. The only possible option left for you is to delete the account in one week.
