### ISSUE TITLE
[BUG] Stickers are not shown

### ISSUE THREAD

**Issue by carlosala** [morethanwords/tweb#196]
**Describe the bug**
I'm using [Ferdium](https://github.com/ferdium/ferdium-app), which is an app like Franz, Ferdi, and this kind of apps that group a bunch of webapps.
I cannot see stickers. I could see them maybe 2 months ago, I'm not sure what changed from that.
Every other kind of animation works, and also reactions, animated emojis... Everything, the only thing that doesn't work are stickers.

**To Reproduce**
1. Type an emoji.
2. See that stickers do not appear.
3. It also happens with a sent sticker.

**Expected behavior**
See stickers.

**Screenshots**
![Screenshot from 2023-01-25 08-28-02](https://user-images.githubusercontent.com/66907184/214504957-842e1a33-020c-4816-93b4-7238b7f09faa.png)

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)
 - Browser Chromium-like (Ferdium)
 - Version 108.0.5359.179

**Comment by carlosala** [comment]
@morethanwords do you know why might happen?

**Comment by morethanwords** [comment]
Try to open this stickerpack: https://t.me/addstickers/Crocosaurus. If you don't see playable stickers there, it could mean that your browser is missing WebAssembly.

**Comment by carlosala** [comment]
It seems like WebAssembly is missing, I'll try to check.

**Comment by carlosala** [comment]
I see that every time that it tries to render something, I get the following error:
```
rlottiePlayer.ts:397 RLottiePlayer renderFrame error: TypeError: Cannot read properties of undefined (reading 'append')
    at rlottiePlayer.ts:642:55
    at Array.forEach (<anonymous>)
    at addEventListener.once [as callback] (rlottiePlayer.ts:642:17)
    at u.invokeListenerCallback (eventListenerBase.ts:127:25)
    at eventListenerBase.ts:165:29
    at Array.forEach (<anonymous>)
    at u._dispatchEvent (eventListenerBase.ts:159:12)
    at u.dispatchEvent (eventListenerBase.ts:185:10)
    at u.renderFrame2 (rlottiePlayer.ts:395:12)
    at u.renderFrame (rlottiePlayer.ts:436:10) 140 140
```
Might this be related? Thanks @morethanwords !

**Comment by carlosala** [comment]
@morethanwords I remember that it was working at some point maybe 2 or 3 months ago, may it be because of some change to this RLottie?

**Comment by carlosala** [comment]
Maybe [this commit](https://github.com/morethanwords/tweb/commit/866d1c05ef30c7a8b67ad5467380e52b942d381b) that changed a lot the Rlottie implementation.
