### ISSUE TITLE
[BUG] RMB menu to schedule/silent send vanishes in new attach pic panel

### ISSUE THREAD

**Issue by Younes-L** [morethanwords/tweb#200]
**Describe the bug**
Since 7c988c4 (291) , trying to schedule or send a picture without sound, the menu is closed immediately before can click with mouse.

**To Reproduce**
1. Go to any chat where can send picture
2. Click on 📎 attach button and select a picture.
    Or, paste a picture from clipboard 
3. Make sure the pic is being sent compressed (default, "as media", not "as file")
4. Right click the "send" button in the attach panel
5. Click "send without sound" or "schedule message"

**Expected behavior**
User is able to click "send without sound" or "schedule message"

**Actual behaviour**
The right click menu disappears as soon as mouse starts moving towards it.  
Additionally , the menu appears in a weird position : same position as the `...` overflow menu, instead of appearing close to the send button.

**Screenshots**
![image](https://user-images.githubusercontent.com/23421600/216427628-c5561107-acc9-4a42-b2ad-a5838c3d06b1.png) ![image](https://user-images.githubusercontent.com/23421600/216428173-acc3a424-b6bf-4409-8435-7937a2971457.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser : Firefox 102
 - WebK version : 291, 298, 301

**Comment by morethanwords** [comment]
Fixed in build 302.
