### ISSUE TITLE
Proxy Support Problem

### ISSUE THREAD

**Issue by PBhadoo** [morethanwords/tweb#201]
To overcome Blocks I've used Proxy to connect to this app and deployed it.

Deployed at https://telegramweb1.netlify.app

Proxy are like https://telegramweb1.netlify.app/venus/ for venus.web.telegram.org (works fine, some requests i see using this in app)

But it keeps connecting to kws2.web.telegram.org and similar urls in websocket mode.

while there is no mention of this url in your code.

**Comment by zengzhichao233** [comment]
May I ask how you configured the proxy?
