### ISSUE TITLE
[BUG] Sometimes accentuation doesn't work when writing a message

### ISSUE THREAD

**Issue by Lkzeu** [morethanwords/tweb#219]
When writing a message trying to accentuate the first letter leads to delete the line. 

**To Reproduce**
   1. Enter in a chat (group or private);
   2. Try to type anything that starts with an accentuated letter;
   3. See it sometimes deleting the line or sometimes writing it correctly.
   4. Occurs regardless of whether you type it fast or slow!

**Expected behavior**
ALWAYS write the message as typed.

**GIF:**
trying to start the message with 'é' 
![bug](https://user-images.githubusercontent.com/52470996/226771631-d6fd7b7c-1196-44e9-b841-812badcff8ac.gif)

**Desktop:**
 - OS: Linux Mint 21.1 'Vera' - xfce
 - Browser: Mozilla Firefox
 - Version: 110.0 (64-bits)

**Additional context**
It only occurs when the first letter is accentuated. Trying to type "Só", "vários", etc, just work as expected.

**Comment by gordinho25** [comment]
E

**Comment by gordinho25** [comment]
Uploading 5236992047542571480_play.mp4_logo_BR.mp4…

**Comment by gordinho25** [comment]
E
