### ISSUE TITLE
[BUG] Static adaptive emojis does not match text color

### ISSUE THREAD

**Issue by osipxd** [morethanwords/tweb#224]
**Describe the bug**
I have static adaptive emojis pack: https://t.me/addemoji/RaReillyAdaptive
According to the adaptive emoji definition:

- Image color should be ignored
- emoji should match the text color

But it isn't

**To Reproduce**
1. Go to 'https://t.me/addemoji/RaReillyAdaptive'
2. Look at emojis

**Expected behavior**
Emojis match the text color. White if you use bark theme and black if you use light theme.

**Screenshots**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/3684355/232485125-48e23311-9aaa-4dc2-b302-388e9aa9826b.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Browser: Google Chrome 111.0.5563.64
 - Version: 1.7.0 (273)

**Comment by osipxd** [comment]
Link with:
- https://github.com/Ajaxy/telegram-tt/issues/245
- https://github.com/overtake/TelegramSwift/issues/962

**Comment by konfetaz** [comment]
+1 bug on iphone

**Comment by morethanwords** [comment]
Implemented in 1.8.0.
