### ISSUE TITLE
[BUG] no git tag, checkout history commit ,build failed

### ISSUE THREAD

**Issue by 315567599** [morethanwords/tweb#235]
**Describe the bug**
> git checkout b04d3259

> npm start

ERROR in ./src/components/sidebarLeft/tabs/privacyAndSecurity.ts
Module not found: Error: Can't resolve './privacy/phoneNumber' in '/Users/jiangchao/work/repo/misc/tweb-k/src/components/sidebarLeft/tabs'
 @ ./src/components/sidebarLeft/tabs/privacyAndSecurity.ts 10:0-61 135:24-48
 @ ./src/components/sidebarLeft/tabs/settings.ts
 @ ./src/components/sidebarLeft/index.ts
 @ ./src/lib/appManagers/appDialogsManager.ts
 @ ./src/pages/pageIm.ts
 @ ./src/index.ts

ERROR in /Users/jiangchao/work/repo/misc/tweb-k/src/components/sidebarLeft/tabs/privacyAndSecurity.ts
./src/components/sidebarLeft/tabs/privacyAndSecurity.ts 12:37-60
[tsl] ERROR in /Users/jiangchao/work/repo/misc/tweb-k/src/components/sidebarLeft/tabs/privacyAndSecurity.ts(12,38)
      TS2307: Cannot find module './privacy/phoneNumber' or its corresponding type declarations.
Child HtmlWebpackCompiler:

**Comment by morethanwords** [comment]
The file wasn't included for a while. Pull it from master.
