### ISSUE TITLE
[BUG] It seems that K-web version stopped working with video calls

### ISSUE THREAD

**Issue by IhostVlad** [morethanwords/tweb#245]
**Describe the bug**
It seems that K-web version video calls stopped working between app-based versions (windows app, android app)

**To Reproduce**
1. For pure experiment, uninstall windows/android app on one side, uninstall chromium-based browser and wipe all cache/data on another side, and re-install fresh versions of software above
2. Try to perform video call between web-browser with Telegram web version and android/windows app in any direction
3. If perform call from web-browser with Telegram web version and android/windows app, error will appear on app side. In reverse case error will appear in browser
4. Error message advice to update telegram, however, fresh version of software have been installed in Step 1
5. Perform video call between windows and android apps - all works fine, no network and streaming video/audio issues

**Expected behavior**
Web version should work with video calls as well as app versions

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - Browser: Microsoft Edge 109.0.1518.155 official release (tested on other chromium-based browsers with same effect)
 - Version: http://web.telegram.org/k/

**Additional context**
Web version works well for many months until last weekend, then error had become appeared

Error message content in russian is "К сожалению, Ваша версия приложения не позволяет принять этот звонок. Пожалуйста, обновите Telegram: telegram.org/upgrade"

**Comment by Evgeni9229** [comment]
Got the same bug, the K-web version in any web-browser doesnt work with windows/android/ios app version.

**Comment by PetroBulbash** [comment]
This error occurs not only when making video calls, but also audio calls.

**Comment by ahbali** [comment]
I am facing the same issue, audio and video calls are not working from and to telegram web k. 
(Telegram-Desktop also have the same issue)
i get this error:
![telegram_desktop_error](https://github.com/morethanwords/tweb/assets/34171431/24619143-9756-4120-a5ae-99c007b5d928)
The mobile apps (ios && android) are not affected by this issue
