### ISSUE TITLE
Not able to compile the repo

### ISSUE THREAD

**Issue by mr-villian08** [morethanwords/tweb#249]
I clone this project on my system and cannot compile it. It giving me the following error.

1.  **ERROR in ./src/index.ts** Please check the screenshot below:-
https://github.com/morethanwords/tweb/assets/87607534/eea24766-322a-4024-bed9-c6e1e5beed9b

@morethanwords @AlexWebArchitect @ruslan-gennadievich

**Comment by DittmerOk** [comment]
add to jsconfig     "noEmit":false,

**Comment by morethanwords** [comment]
See https://github.com/morethanwords/tweb/issues/269#issuecomment-1825995116.
