### ISSUE TITLE
[BUG] Send by enter 

### ISSUE THREAD

**Issue by SrW0nka** [morethanwords/tweb#26]
**Describe the bug**
Send by enter dont work with caption

**To Reproduce**
1. Go to a random chat (whatever)
2. Click on "photo or video" or just make a ctrl V
4. Add a caption
4. See error: when you press enter to send the site just drop one line

**Expected behavior**
Send the message

**Screenshots**
![image](https://user-images.githubusercontent.com/76596575/118653988-79333380-b7be-11eb-9d4e-5e4b946065a3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.24.85

**Additional context**
![image](https://user-images.githubusercontent.com/76596575/118653834-4e48df80-b7be-11eb-9486-9550f07d892a.png)

**Comment by morethanwords** [comment]
Thank you for the report! Should be fixed now.
