### ISSUE TITLE
Feature request: Ability to change theme colors (especially on dark mode)

### ISSUE THREAD

**Issue by Pawel-Dymek** [morethanwords/tweb#3]
Dark mode now have very strange colors: purple on the menu elements on the left, and some kind of brownish orange on the sender messages.
Imho it's just weird and I would very much like to have an ability to change that.

Thanks in advance for taking it into consideration

**Comment by morethanwords** [comment]
Thanks for your suggestion! By the way, there is a lot better place for it, could you please post it on the [platform](https://bugs.telegram.org/?tag_ids=40&sort=rate), where other people will be able to promote it?
