### ISSUE TITLE
[BUG] Chats are overscrolled on Firefox

### ISSUE THREAD

**Issue by wheezard** [morethanwords/tweb#303]
**Describe the bug**
Sometimes, when going from one chat to another, you end up further down than the most recent message, causing you to see an empty screen instead of the messages

**To Reproduce**
1. Log in
2. Click on a chat and load some messages above
3. Scroll back down so the most recent message is fully visible
4. Click on another chat (with less loaded messages)
5. You'll see an empty screen,
6. If you scroll up, you'll see the messages.

**Expected behavior**
In Chrome, it works as expected - the chats' scroll is always at the bottom when you click on them.

**Screenshots**
![This is what you see in the second chat](https://github.com/morethanwords/tweb/assets/90904039/a1e2f1b9-74f1-40d5-833c-7bacad5af74b)
![This is what you see in the second chat after you scroll](https://github.com/morethanwords/tweb/assets/90904039/80b9b416-4ddb-4321-8180-2e9abcdb1b39)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 122.0.1
 - Version of Telegram Web: 2.0.0 (482)

**Comment by morethanwords** [comment]
Fixed.
