### ISSUE TITLE
[BUG] Typing :D<ENTER> results in dress being added to a post instead of very common emoji.

### ISSUE THREAD

**Issue by swistak** [morethanwords/tweb#31]
**Describe the bug**

Typing in :D at the end of the message and hitting <enter> results in dress being added to a post. 

:D is a very common emoji and having it change to a dress by default makes no sense.

**To Reproduce**

1. Type a message
2. Add a broad smile :D
3. Hit an enter
4. Dress shows up.

**Expected behavior**

Message should be sent with a broad smile 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any (Windows)
 - Browser: Firefox
 - Version: Current

**Comment by morethanwords** [comment]
Thank you for the report! Should be fixed now.
