### ISSUE TITLE
[BUG] [TMA] Back Button is hiding automatically after being clicked

### ISSUE THREAD

**Issue by heyqbnk** [morethanwords/tweb#310]
**Describe the bug**
At the moment, clicking the Back Button leads to its hiding even without calling the `web_app_setup_back_button` method.

**To Reproduce**
1. Open the mini app: https://t.me/tmajsbot/react_example
2. Go to **Launch Params** -> **Init Data** (_View_)
3. Click the Back Button
4. Back Button is hiding, but the `web_app_setup_back_button` method was not called

**Expected behavior**
The Back Button is not hiding automatically after being clicked.

**Screenshots**
`-`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Yandex Browser (Chromium)
 - Version: 120.0.6099.911

**Smartphone (please complete the following information):**
`-`

**Additional context**
You could try the steps to reproduce in other Telegram applications to see that Web K is the only 1 having this issue. Just to make sure, the application is not calling any methods to hide the Back Button.

**Comment by morethanwords** [comment]
Thank you for the report! Fixed now.
