### ISSUE TITLE
[BUG] User status keeps appending "when" while the user is typing

### ISSUE THREAD

**Issue by richardrigutins** [morethanwords/tweb#311]
**Describe the bug**
On the _User Info_ panel, when the user is typing or selecting a sticker, a series of _when?_ strings keep getting added to the user status while the user keeps typing.

Only a single _when?_ is displayed instead when the status changes to a different value (online, last seen recently).

**To Reproduce**
1. Open a chat with a user.
2. Click on the user name or profile picture on the top bar to open the _User Info_ panel.
3. Have the user type a message for some seconds.
4. The user status is displayed as _typing_, and multiple _when?_ elements are progressively appended to the status.

**Expected behavior**
Only a single _when?_ element should be displayed.

**Screenshots**
![image](https://github.com/morethanwords/tweb/assets/47950599/ced90f01-74cf-4fa9-a1fd-f9c01b56e989)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge
 - Version 122

**Smartphone (please complete the following information):**

**Additional context**
The behavior could be caused by a conflict between the code block that appends the _when_ element in `peerProfile.ts`:
```
          const when = i18n('StatusHiddenShow');
          when.classList.add('show-when');
          attachClickEvent(when, (e) => {
            cancelEvent(e);
            PopupElement.createPopup(PopupToggleReadDate, peerId, 'lastSeen');
          });
          this.subtitle.append(when);
```

and this check inside `setPeerStatus` in `appImManager.ts`:
```
      const typingContainer = element.querySelector('.peer-typing-container') as HTMLElement;
      if(typingContainer && await this.getPeerTyping(peerId, typingContainer)) {
        // log('already have a status');
        return;
      }
```

Because of this check, the _subtitle_ element doesn't get replaced while the user is typing, but a _when_ element keeps getting appended to it.
When the user is not typing, the _subtitle_ is replaced after every update, and only a single _when_ element is displayed.

**Comment by Waynaade** [comment]
> **Describe the bug** On the _User Info_ panel, when the user is typing or selecting a sticker, a series of _when?_ strings keep getting added to the user status while the user keeps typing.
> 
> Only a single _when?_ is displayed instead when the status changes to a different value (online, last seen recently).
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open a chat with a user.
> 2. Click on the user name or profile picture on the top bar to open the _User Info_ panel.
> 3. Have the user type a message for some seconds.
> 4. The user status is displayed as _typing_, and multiple _when?_ elements are progressively appended to the status.
> 
> **Expected behavior** Only a single _when?_ element should be displayed.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/47950599/317013720-ced90f01-74cf-4fa9-a1fd-f9c01b56e989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTU4MTUsIm5iZiI6MTcxMjQ1NTUxNSwicGF0aCI6Ii80Nzk1MDU5OS8zMTcwMTM3MjAtY2VkOTBmMDEtNzRjZi00ZmE5LWExZmQtZjljMDFiNTZlOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTllYzY5NzMyZDIzNjIwODk4MjM1NWNhMjM4MTE3MGNlMWM3ZGE4YmI1ZjYyYWU0YTVkZDk5NjYxMzk0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPX0450U6T2340nG9lkWVJe968kDmJ6QLBG9_919k1g)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser Chrome, Edge
> * Version 122
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** The behavior could be caused by a conflict between the code block that appends the _when_ element in `peerProfile.ts`:
> 
> ```
>           const when = i18n('StatusHiddenShow');
>           when.classList.add('show-when');
>           attachClickEvent(when, (e) => {
>             cancelEvent(e);
>             PopupElement.createPopup(PopupToggleReadDate, peerId, 'lastSeen');
>           });
>           this.subtitle.append(when);
> ```
> 
> and this check inside `setPeerStatus` in `appImManager.ts`:
> 
> ```
>       const typingContainer = element.querySelector('.peer-typing-container') as HTMLElement;
>       if(typingContainer && await this.getPeerTyping(peerId, typingContainer)) {
>         // log('already have a status');
>         return;
>       }
> ```
> 
> Because of this check, the _subtitle_ element doesn't get replaced while the user is typing, but a _when_ element keeps getting appended to it. When the user is not typing, the _subtitle_ is replaced after every update, and only a single _when_ element is displayed.

Ok

**Comment by Waynaade** [comment]
Good
