### ISSUE TITLE
[BUG] Complete Emoji Sequences such as :joy: do not trigger emoji popover

### ISSUE THREAD

**Issue by Ferdi265** [morethanwords/tweb#33]
**Describe the bug**
When typing emoji sequences such as `:joy:` :joy: or `:sweat_smile:` :sweat_smile:, the emoji popover disappears as soon as the final `:` is typed, making it impossible to select :joy: without mouse input (pressing enter at `:joy` creates `:joystick:` :joystick:).

**To Reproduce**
1. Write a new message
2. Type `:joy`
3. Observe popover
4. Type final `:`, text is now `:joy:`
5. Observe popover disappearing

**Expected behavior**
The popover should still be visible directly after the final `:` is typed so an exactly named emoji can be inserted.

**Screenshots**

Partial Emoji Sequence:
![partial](https://user-images.githubusercontent.com/4077106/122307949-a6811780-cf0b-11eb-98f5-b466b2c9cab5.png)

Complete Emoji Sequence:
![complete](https://user-images.githubusercontent.com/4077106/122308001-c0225f00-cf0b-11eb-91ff-92cbad7c3e16.png)

**Desktop (please complete the following information):**
 - OS: Linux (Arch Linux)
 - Browser: Firefox 89
 - Version: WebK alpha 0.5.6

**Comment by morethanwords** [comment]
I'm not sure that it is a bug. Any other Telegram client has the same behaviour. However, it is worth to implement auto replacing emoji on sending.
