### ISSUE TITLE
[BUG] application is not reproducible with custom http-only domain

### ISSUE THREAD

**Issue by r4sas** [morethanwords/tweb#35]
**Describe the bug**
Application is not reproducible with custom domain. When I deploy `public` on server with HTTP (not https) access it won't starting.

**To Reproduce**
1. Use node 12 (lts)
2. run `npm i && npm run build`
3. publish `public` folder to website without ssl support
4. find error in devtools

**Expected behavior**
Runnable telegram web application

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 89

**Additional context**
Console output from devtools:

```
logger.ts:44 [3.129] [API-PROXY]: WORKER ERROR ErrorEvent {isTrusted: true, message: "Uncaught ReferenceError: caches is not defined", filename: "http://tgweb.local/mtproto.worker.2fda2f3995e9e0f73938.bundle.worker.js", lineno: 3, colno: 316147, …}
s.error @ logger.ts:44
(anonymous) @ mtprotoworker.ts:319
error (async)
registerWorker @ mtprotoworker.ts:318
(anonymous) @ mtprotoworker.ts:191
13 @ mtprotoworker.ts:543
r @ bootstrap:63
11 @ langPack.ts:1
r @ bootstrap:63
Promise.then (async)
(anonymous) @ index.ts:110
(anonymous) @ main.2246262129bd79d2031c.bundle.js:1
s @ main.2246262129bd79d2031c.bundle.js:1
(anonymous) @ index.ts:39
```

**Comment by patrizok** [comment]
Same Problem, while connecting with localhost or 127.0.0.1 there is no problem but when I access with server ip from local machine or access from remote machine I get the same error.

To serve npm builded public folder I use: `node server.js 0 8000 http`

**Comment by morethanwords** [comment]
That's because the application is designed to work HTTPS-only. There are several browser's APIs that require secure context (e.g. [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage), [cryptographic functions](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto)).
