### ISSUE TITLE
[BUG] Blank page in Firefox

### ISSUE THREAD

**Issue by aerdnar** [morethanwords/tweb#4]
There is something wrong with Firefox, errors in console and blank page

**Comment by morethanwords** [comment]
What is the version of Firefox?

**Comment by aerdnar** [comment]
FF85 on linux, FF87 and FF88 on windows. 
How to reproduce: 
open webk.telegram.org in private mode, refresh the page.

This is my console log:
[console-export-2021-4-23_13-39-3.txt](https://github.com/morethanwords/tweb/files/6364976/console-export-2021-4-23_13-39-3.txt)

**Comment by morethanwords** [comment]
Thanks! I've installed FF64 and fixed the bug. It is nothing with these logs (seems IndexedDB doesn't work in FF's private mode), just layout issue. Soon on live.

**Comment by morethanwords** [comment]
Please try again, should be fixed.

**Comment by aerdnar** [comment]
same as before, sometimes it works and sometimes not.

When it works there are these in console
`got state, time: 425 index.ts:264:12`
`Will mount auth page: authStateSignIn 1619194582.736 index.ts:268:14`

When it fails there is this in console
`Uncaught (in promise) something went wrong`

> Uncaught (in promise) something went wrong main.c5de0cf63914a3455e51.bundle.js:1:4478
    c main.c5de0cf63914a3455e51.bundle.js:1
    (Asinc.: promise callback)
    s main.c5de0cf63914a3455e51.bundle.js:1
    a main.c5de0cf63914a3455e51.bundle.js:1
    (Asinc.: promise callback)
    s main.c5de0cf63914a3455e51.bundle.js:1
    c main.c5de0cf63914a3455e51.bundle.js:1
    c main.c5de0cf63914a3455e51.bundle.js:1
    <anonima> index.ts:37
    (Asinc.: EventListener.handleEvent)
    <anonima> index.ts:37
    Webpack 3

**Comment by morethanwords** [comment]
Oh, I did say about storage and didn't check the exception, I'm sorry. Please try again.

**Comment by aerdnar** [comment]
Now it works, thanks!
