### ISSUE TITLE
[BUG] Shared phone number break the screen 

### ISSUE THREAD

**Issue by SrW0nka** [morethanwords/tweb#40]
**Describe the bug**
When click in shared phone number, the site crash and "split" the screen 

**To Reproduce**

1. Click on some shared phone number

2. See error

**Expected behavior**
Tbh idk

**Screenshots**
![image](https://user-images.githubusercontent.com/76596575/124362834-e0416600-dc0d-11eb-94fe-c5b363699c94.png)
![image](https://user-images.githubusercontent.com/76596575/124362856-06670600-dc0e-11eb-8788-714d13a566cc.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brave
 - Version: Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)

**Comment by SrW0nka** [comment]
Seems my screen shoot get a little bit corrupted, just ignore this crazy yellow bug

**Comment by morethanwords** [comment]
Thank you for the report! Should be fixed in 0.9.1 (25).
