### ISSUE TITLE
[BUG] Doesn't work anymore on old Chromium 73.0.3683.75

### ISSUE THREAD

**Issue by safinaskar** [morethanwords/tweb#48]
**Describe the bug**
I use old Chromium version (73.0.3683.75), because this is latest Chromium version available in my debian release (stretch).

Recently (1-2 days ago) web telegram K stopped to work in this version.

**To Reproduce**
Open Chromium 73.0.3683.75 (in debian stretch).
Open web.telegram.org/k (I already logged in).

**Expected behavior**
Normal working web client

**What I see**
I see nearly empty page instead: two empty panels.
And the following message in console:
```
Uncaught (in promise) TypeError: Failed to execute 'setActionHandler' on 'MediaSession': The provided value 'stop' is not a valid enum value of type MediaSessionAction.
    at new <anonymous> (appMediaPlaybackController.ts:74)
    at Module.137 (appMediaPlaybackController.ts:485)
    at a (bootstrap:63)
```

**Desktop (please complete the following information):**
 - OS: debian
 - Browser chromium 73.0.3683.75

**Comment by morethanwords** [comment]
Thank you for the report! Please try again, should be fixed.

**Comment by safinaskar** [comment]
It works, thanks
