### ISSUE TITLE
[Feature Request] Make it possible to add people to contacts without knowing their phone number

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#49]
**Is your feature request related to a problem? Please describe.**
I cannot add people to contacts if I don't know their phone number. This is possible to do in other clients (e.g. Android client).

**Describe the solution you'd like**
Make it possible to add anyone to contacts if I open their profile (e.g. they send a message to me, or I can see their message in a group, etc.)

**Describe alternatives you've considered**
A fix for #45 added a way to add contacts by phone number. This doesn't work if you don't know the phone number.

**Additional context**
Currently, when viewing a profile of someone who is in the contacts, there is an "edit contact" button. When viewing a profile of someone who is *not* in the contacts, this button is hidden using `display: none`. It is possible to unhide this button using developer tools, and then use it to add this person to contacts (click it, make some changes and save). This feature request is to make it possible to do the same without resorting to hacks.

**Comment by morethanwords** [comment]
You can see the button in chat menu:

![Screenshot 2021-09-26 at 20 06 30](https://user-images.githubusercontent.com/25210241/134815388-76c6fae4-42c3-4319-ae23-75a381c024c4.png)

**Comment by abacabadabacaba** [comment]
I see. The interface is pretty non-intuitive, though: to add a contact you need to use the chat menu, but to edit/delete the existing one you need to click a button in the side bar. It would be better if both functions could be accessed from the same place (e.g. in Android client both are in the profile menu).

**Comment by morethanwords** [comment]
It is. Tried to match Android' design, though it doesn't fit to desktop layout. Maybe buttons Add and Block will be moved to profile (as on macOS).
