### ISSUE TITLE
[BUG] How to disable websocket and enable https?

### ISSUE THREAD

**Issue by realkimmy** [morethanwords/tweb#59]
How to disable `websocket` and enable `https`?

![screenshot-20211018-151101](https://user-images.githubusercontent.com/19725091/137684861-99b18c6d-80ea-4145-b76e-8da3842bd5c2.png)

![screenshot-20211018-151231](https://user-images.githubusercontent.com/19725091/137685180-e0d4b397-33a6-46a2-afda-2bc12b9e300b.png)

**Comment by karevan** [comment]
i have this question :(

**Comment by morethanwords** [comment]
Has been fixed in 1.0.0 (42). Application now automatically detects available transport between WebSocket and HTTPS.

**Comment by karevan** [comment]
I have a question regarding the Telegram Web K version. I noticed that it supports both WebSocket and HTTP protocols for communication with the server. Could you please explain why both protocols are used simultaneously in the web version? What are the specific advantages of using WebSocket alongside HTTP for this purpose?

Thank you in advance for your clarification!
