### ISSUE TITLE
[Feature Request] Audio messages on Webkit (Safari & Co.)

### ISSUE THREAD

**Issue by Tuxino88** [morethanwords/tweb#6]
I'm using WebKit satisfaction creating a webapp of your project, unique problem are missing audio messages.

The broweser is gnome-web of whose engine is webkit2-gtk3, I gave access permissions to the microphone but the record key does not appear
![Schermata da 2021-04-26 10-27-29](https://user-images.githubusercontent.com/75674245/116052747-36c47e00-a67a-11eb-850f-002b377f868c.png)

**Comment by legacychimera247** [comment]
Yep, i second this as it would be a nice feature to have...

**Comment by morethanwords** [comment]
Please check if your browser supports WebAssembly, it is definitely needed to record them

**Comment by Tuxino88** [comment]
> Please check whether your browser supports WebAssembly, it is definitely needed to record them

I am not a technician but from their site it seems that it is supported

[https://webkit.org/blog/7691/webassembly/](webkit webassembly)
