### ISSUE TITLE
[BUG] When trying to check folder tab with several chats it's loading forever

### ISSUE THREAD

**Issue by erbanku** [morethanwords/tweb#64]
**Describe the bug**

When trying to check folder tab with several chats it's loading forever

**To Reproduce**

1. Go to tab with different types of chats
2. Get an issue with loading

**Expected behavior**

Loading chat folders normally

**Screenshots**

<p align=center>
  <img src="https://user-images.githubusercontent.com/79493862/140844830-f10cb831-74db-4794-90f7-ab5a2ca2f23a.gif" width="60%"/>
</p>

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: Chrome 95
 - Telegram WebK 0.9.1.22

**Additional context**
You can also see the bug report here: https://bugs.telegram.org/c/10550

**Comment by Aledarit** [comment]
Same issue with Windows 10

**Comment by morethanwords** [comment]
Thank you for the report! Could you please provide a screenshot with folder's settings?

**Comment by erbanku** [comment]
@morethanwords 

![](https://user-images.githubusercontent.com/79493862/141215791-095525c7-bd73-448f-8696-3b4b65b9afff.png)

**Comment by erbanku** [comment]
### A very strange bug 😅

**Comment by morethanwords** [comment]
> ### A very strange bug 😅

That's true. Still don't have a clue. Are you able to contact me on [Telegram](https://t.me/kuzm3nko), so I'll be able to investigate it deeper?

**Comment by erbanku** [comment]
OK 👌

**Comment by erbanku** [comment]
@Aledarit This issue fixed in version 0.9.1 (26)
