### ISSUE TITLE
[BUG] Emojis in admin names are displayed incorrectly

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#66]
**Describe the bug**
When viewing [this message](https://t.me/tginfo/3151) in Telegram Web K, I see the following:

![image](https://user-images.githubusercontent.com/8302078/141804506-30e225dc-fc35-49a3-90a1-4ac7421544ba.png)

**Expected behavior**

An emoji in the admin's name should be displayed correctly.

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 91.3

**Comment by morethanwords** [comment]
Thank you for the report! What is the version and build number of application?

**Comment by abacabadabacaba** [comment]
I tried to check, and I cannot reproduce the issue anymore. Looks like it was fixed by [this commit](https://github.com/morethanwords/tweb/commit/018fb2a1b34542197c62c55813ed2f376b15cd8e).
