### ISSUE TITLE
[BUG] Right click triggers browser's context menu

### ISSUE THREAD

**Issue by forkbomb9** [morethanwords/tweb#7]
**Describe the bug**
When right-clicking any element to trigger WebK's context menu, the browser's context menu pops up on top, making it impossible to use WebK's context menu. Upon left-clicking off the browser's menu, it disappears, thus making WebK's menu available.

**To Reproduce**
1. Right-click on any message or chat
2. Both WebK's and browser's context menu pop up
3. Left-click outside browser's menu
4. WebK's menu is available

**Expected behavior**
Right-clicking chats or messages trigger only WebK's context menu

**Screenshots**
![2021-04-28-190749_screenshot_blurred](https://user-images.githubusercontent.com/33267474/116487462-8aec7f80-a87f-11eb-8516-db753f59260d.png)
![2021-04-28-190755_screenshot_blurred](https://user-images.githubusercontent.com/33267474/116487466-8d4ed980-a87f-11eb-90ab-30e7f5f2e79b.png)

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 88

**Comment by morethanwords** [comment]
Seems like it's a linux-only issue. Please provide more details about your OS.

**Comment by forkbomb9** [comment]
Up-to-date Manjaro, with the LibreWolf 88 browser (based on Firefox).
Can be reproduced in Firefox 88 too.

**Comment by forkbomb9** [comment]
Correction: This issue isn't observed on FF 88. Will file an issue on LibreWolf's tracker
