### ISSUE TITLE
[Feature Request] Add support for spoilers

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#74]
**Is your feature request related to a problem? Please describe.**
In the [today's update](https://telegram.org/blog/reactions-spoilers-translations), Telegram added support for spoilers. However, messages with spoilers are not displayed in Telegram Web K.

**Describe the solution you'd like**
Telegram Web K should support spoilers in messages and display them correctly.

**Comment by morethanwords** [comment]
Has been added in 1.0.3.
