### ISSUE TITLE
The session expire in Firefox (Private mode)

### ISSUE THREAD

**Issue by elvus** [morethanwords/tweb#8]
The session expire in private mode when tab close

**Comment by morethanwords** [comment]
What is the browser did you use?

**Comment by elvus** [comment]
Sorry only happens in Firefox
    OS: Windows 10
    Browser: Firefox 88.0 (64-bit)
    browsers it works (Chrome, Chromium)

**Comment by morethanwords** [comment]
Firefox disables storages in private mode, that's why session "expires", application can't save it. If you even reload the page, result will be the same. You can get the same behavior just by turning off the "Keep me signed in" on login.
