### ISSUE TITLE
[Feature Request] Writing messages with spoilers

### ISSUE THREAD

**Issue by abacabadabacaba** [morethanwords/tweb#80]
**Is your feature request related to a problem? Please describe.**
Currently, Telegram Web K can display messages with spoilers, but it is not possible to write such a message.

**Describe the solution you'd like**
It should be possible to format text in a message being written as a spoiler.

**Comment by morethanwords** [comment]
Actually, it is possible by two ways: surround the text with || or using Ctrl+P or Command+P. Will be also possible in markup tooltip soon.

**Comment by abacabadabacaba** [comment]
There are multiple problems with this. First, it is not documented. Second, in the edit box it looks like a text with a gray background, so it is not obvious that it is a spoiler. Third, there is no way to _remove_ spoiler formatting (pressing Ctrl-P second time doesn't work). I think that this issue should be open until at least this functionality is added to the formatting tooltip.

**Comment by morethanwords** [comment]
Spoiler button has been added in markup tooltip, and removing spoiler has been fixed in 1.0.5.

**Comment by hoalinh99** [comment]
Command+P.
