### ISSUE TITLE
[BUG] Loading issues

### ISSUE THREAD

**Issue by afnecors** [morethanwords/tweb#83]
**Describe the bug**
The webapp does not load. It displays the following messages in a loop: "Waiting for network...", "Updating...", "Reconnecting...", the page reloads and starts the cycle again. Note: I can connect to the internet and access other sites. 

In "Network Monitor" there is `GET https://web.telegram.org/k/` with `NS_BINDING_ABORTED` error.

**To Reproduce**
1. Go to [https://web.telegram.org/k/](https://web.telegram.org/k/)
3. See screenshot

**Expected behavior**
Open the webapp.

**Screenshots**
![telegram_k_web_bug](https://user-images.githubusercontent.com/3373979/151139058-40c9fb5c-49d1-4866-94b9-fe60bc6a2341.gif)

**Desktop:**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version: 96.0 (64-bit)

**Comment by theuserbl** [comment]
Confimed.
I have the same problem with Firefox on Windows 10.
But on Microsoft Edge with Chromium basis, it works perfect.
So the web version of telegram no longer likes the Firefox engine. :-/
