### ISSUE TITLE
[BUG] Consecutive newlines are lost when composing

### ISSUE THREAD

**Issue by pcworld** [morethanwords/tweb#89]
**Describe the bug**
When sending a message, entering multiple consecutive newlines (via Shift-Return) get lost after sending (are replaced by a single newline).

**To Reproduce**
1. Open a chat
2. Write message `a\n\nb` (where `\n` indicates a newline as entered by Shift-Return)
3. Press Return to send the message.
4. The message sent is `a\nb`, the empty line is lost.

**Expected behavior**
The message sent should be `a\n\nb` (where `\n` indicates a newline).

**Screenshots**
Composing:
![image](https://user-images.githubusercontent.com/1506734/154698826-5585ce3d-a690-41a6-8edb-72d40ac682c8.png)
Actually sent message:
![image](https://user-images.githubusercontent.com/1506734/154698892-54301270-973e-426a-bb39-190b5df97bcc.png)

**Desktop**
 - OS: Ubuntu 20.04
 - Browser: Firefox 97.0

**Additional context**
After reproduction step 2, copying the message and then pasting it again also loses the empty line (Ctrl-A Ctrl-C Ctrl-V). When pasting the contents into an external application, the empty line is not lost.
Further, when composing `a\n\nb` in an external application, copying it and then pasting it into the Telegram client, the empty line is also not lost.

**Comment by valerio-bozzolan** [comment]
I can reproduce on latest version of https://web.telegram.org/k/ in whatever chat.

If you want to reproduce quickly, copy this as new message:

```
Test

Toast
```

Then you will see this as sent message:

```
Test
Toast
```

Thank you for what you can do.

**Comment by valerio-bozzolan** [comment]
Hi @morethanwords just a question. Can you reproduce? Thanks :)

**Comment by valerio-bozzolan** [comment]
Please mark this as resolved! Thank you so much! It works perfectly now

**Comment by valerio-bozzolan** [comment]
Just as interesting note, this was probably fixed by this commit:

https://github.com/morethanwords/tweb/commit/493897fbd307c09556091a414e7758e6240c7b77

**Comment by morethanwords** [comment]
> Just as interesting note, this was probably fixed by this commit:
> 
> [493897f](https://github.com/morethanwords/tweb/commit/493897fbd307c09556091a414e7758e6240c7b77)

No, it was fixed [here](https://github.com/morethanwords/tweb/commit/6a5ffb44b1fee517ea6a35a637e8041e62443570#diff-c96cdd9a5767d1e563ff98468304c1684ec21ccf58b27b2e4cc8670ea3cd4c2cR186)
