### ISSUE TITLE
[Feature Request] Add full RTL support

### ISSUE THREAD

**Issue by yarons** [morethanwords/tweb#9]
Hebrew, Arabic, Persian, Urdu and several others use scripts written from right to left.

This is a blog post about adjusting Spotify to support these languages:
https://engineering.atspotify.com/2019/04/15/right-to-left-the-mirror-world/

I will start testing it myself and see if I can contribute without breaking the UI completely.

Currently the most important thing is to add `dir=auto` to the input boxes so typing in these languages will be more coherent.

Thank you.

**Comment by morethanwords** [comment]
Thanks for report. Should be fixed now.

**Comment by yarons** [comment]
It is, thank you :)
